Оптимизация...

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1,11 +1,11 @@
-#Functions for bash
+#Bash functions...
 
 ARGS(){
   for val in "$@"; do
-    if [ "${val:0:1}" == "-" ]; then
+    if [[ "${val:0:1}" == '-' ]]; then
       key=${val:1}
     else
-      if ! [ -z "$key" ] ; then
+      if ! [[ -z $key ]]; then
         declare $key="$val"
         unset key
       fi
@@ -17,44 +17,46 @@ GET_PHP(){
   local ver=$1
   local file=$2
   local link=$3
-  if [ -z "$link" ] ; then
-    echo 'http://php.net/releases/...'
-    link=$(curl http://php.net/releases/|grep $ver.tar.bz2|cut -d '"' -f2)
+  if [[ -z $link ]]; then
+    local page='http://php.net/downloads.php'
+    link=$(curl $page|grep $ver.tar.bz2|cut -d '"' -f2)
   fi
-  if [ -z "$link" ] ; then
-    echo 'http://php.net/downloads.php...'
-    link=$(curl http://php.net/downloads.php|grep $ver.tar.bz2|cut -d '"' -f2)
+  if [[ -z $link ]]; then
+    local page='http://php.net/releases/'
+    link=$(curl $page|grep $ver.tar.bz2|cut -d '"' -f2)
   fi
-  if [ -z "$link" ] ; then
-    echo "PHP ${ver} not found"
-    echo 'Please check correct version!'
-    exit $ERR_FN
-  fi
-  link="http://php.net"$link
-  local links=$(curl $link|grep $ver.tar.bz2|cut -d '"' -f4)
-  for link in $links; do
-    wget --no-check-certificate -O $file $link
-    if [ -f $file ]; then
-      break
+  if [[ $link == *.tar.bz2 ]]; then
+    echo 'GET: '$link
+    wget -O $file $link
+    if [[ -f $file ]]; then
+      return 0
     fi
-  done
-  if ! [ -f $file ]; then
-    echo "$file Not Found"
-    exit $ERR_FN
   fi
-  return 0
+  if [[ -n $link ]]; then
+    link='http://php.net'$link
+    local links=$(curl $link|grep $ver.tar.bz2|cut -d '"' -f4)
+    for link in $links; do
+      echo 'GET: '$link
+      wget -O $file $link
+      if [[ -f $file ]]; then
+        return 0
+      fi
+    done 
+  fi
+  echo 'PHP-'$ver': Not Found!'
+  exit $ERR_FN
 }
 
 CFG_PHP(){
-  local opt=$SRC_DIR'/options-'$2
-  local dst=$1'/options'
-  if ! [ -f $opt ]; then
+  local opt=$SRC_DIR'/options-'$1
+  local dst='./~options'
+  if ! [[ -f $opt ]]; then
     opt=$DIR'/options'
   fi
   cp $opt $dst
-  sed -i -e 's/{ver}/'$2'/g' $dst
-  bash $dst $3 $4
-  if ! [ $? -eq 0 ] ; then
+  sed -i -e 's/{ver}/'$1'/g' $dst
+  bash $dst "$2" "$3"
+  if ! [[ $? -eq 0 ]]; then
     echo 'CONFIGURE?!'
     exit $ERR_FN
   fi
@@ -65,13 +67,12 @@ MAKE_PHP(){
   local ver=$1
   local src=$2
   local dst=$3
-  cd $src
-  CFG_PHP $src $ver
+  CFG_PHP $ver
   make
   make install
-  if ! [ -f $dst'/bin/php-cgi' ] ; then
-   echo 'Error?!'
-   exit $ERR_FN
+  if ! [[ -f $dst'/bin/php-cgi' ]]; then
+    echo 'ERROR?!'
+    exit $ERR_FN
   fi
   return 0
 }
